

export type RootStackParamList = {
    AppointmentScreen: undefined | any,
    ViewAppointmentScreen: undefined | any,
    ViewAppointmentDetailScreen: undefined | any,
    ViewClientHistoryScreen: undefined | any,
    AddToolkitScreen: undefined | any,
    AddStylistScreen: undefined | any,
    StepsForStylist: undefined | any,
    AddStationRoom: undefined | any,
    TransferStylistScreen: undefined | any,
    RatingAndReviewScreen: undefined | any,
    AddItemScreen: undefined | any,
    ServicesScreen: undefined | any,
    MembershipScreen: undefined | any,
    PackageScreen: undefined | any,
    DiscountCardScreen: undefined | any,
    GiftCardScreen: undefined | any,
    ProductScreen: undefined | any,
    BookingConfirmedScreen: undefined | any,
    PaymentMethodScreen: undefined | any,

    HomeScreen: undefined | any,
    ViewTargetScreen: undefined | any,
    NotificationsScreen: undefined | any,

    AttendanceScreen: undefined | any,
    AttendanceHistoryScreen: undefined | any,
    ViewLeaveHistoryScreen: undefined | any,

    TargetScreen: undefined | any,

    ProfileScreen: undefined | any,
    MyProfileScreen: undefined | any,
    PersonalInformationScreen: undefined | any,
    JobProfileScreen: undefined | any,
    WorkingHourScreen: undefined | any,
    TargetPayrollScreen: undefined | any,
    DocumentScreen: undefined | any,
    RatingReviewScreen: undefined | any,

    AppointmentForClientScreen: undefined | any,
    CreateNewAppointmentScreen: undefined | any,
    AddingClientScreen: undefined | any,
    CreateAppointment: undefined | any,
    GuestProfileScreen: undefined | any,
    AddGuestScreen: undefined | any,
    OtherDetailsScreen: undefined | any,
    InsuranceScreen: undefined | any,
    SalaryScreen: undefined | any,
    BankDetailScreen: undefined | any,
    SalaryDetailScreen: undefined | any,
    TermConditionScreen: undefined | any,
    ServiceAvailScreen: undefined | any,
    BusinessLogScreen: undefined | any,
    ClientLogScreen: undefined | any,
    IncentiveEarnedScreen: undefined | any,
    SettingWorkingHourScreen: undefined | any,
    TrainingScreen: undefined | any,
    TrainingVideoScreen: undefined | any,
    ExploreAllTrainingVideos: undefined | any,
    ManageToolKitScreen: undefined | any,
    ReceivedToolkitScreen: undefined | any,
    RequestToolkitScreen: undefined | any,
    ReturnToolkitScreen: undefined | any

};

export const SCREENS = {
    AppointmentScreen: 'AppointmentScreen',
    ViewAppointmentScreen: 'ViewAppointmentScreen',
    ViewAppointmentDetailScreen: 'ViewAppointmentDetailScreen',
    ViewClientHistoryScreen: 'ViewClientHistoryScreen',
    AddToolkitScreen: 'AddToolkitScreen',
    AddStylistScreen: 'AddStylistScreen',
    StepsForStylist: 'StepsForStylist',
    AddStationRoom: 'AddStationRoom',
    TransferStylistScreen: 'TransferStylistScreen',
    HomeScreen: 'HomeScreen',
    ViewTargetScreen: 'ViewTargetScreen',
    DocumentScreen: 'DocumentScreen',

    AttendanceScreen: 'AttendanceScreen',
    AttendanceHistoryScreen: 'AttendanceHistoryScreen',
    ViewLeaveHistoryScreen: 'ViewLeaveHistoryScreen',
    TargetScreen: 'TargetScreen',
    ProfileScreen: 'ProfileScreen',
    AppointmentForClientScreen: 'AppointmentForClientScreen',
    CreateNewAppointmentScreen: 'CreateNewAppointmentScreen',
    AddingClientScreen: 'AddingClientScreen',
    CreateAppointment: 'CreateAppointment',
    GuestProfileScreen: 'GuestProfileScreen',
    AddGuestScreen: 'AddGuestScreen',
    MyProfileScreen: 'MyProfileScreen',
    PersonalInformationScreen: 'PersonalInformationScreen',
    TargetPayrollScreen: 'TargetPayrollScreen',
    JobProfileScreen: 'JobProfileScreen',
    WorkingHourScreen: 'WorkingHourScreen',
    RatingReviewScreen: 'RatingReviewScreen',
    OtherDetailsScreen: 'OtherDetailsScreen',
    InsuranceScreen: 'InsuranceScreen',
    SalaryScreen: 'SalaryScreen',
    BankDetailScreen: 'BankDetailScreen',
    SalaryDetailScreen: 'SalaryDetailScreen',
    TermConditionScreen: 'TermConditionScreen',
    ServiceAvailScreen: 'ServiceAvailScreen',
    BusinessLogScreen: 'BusinessLogScreen',
    ClientLogScreen: 'ClientLogScreen',
    IncentiveEarnedScreen: 'IncentiveEarnedScreen',
    SettingWorkingHourScreen: 'SettingWorkingHourScreen',
    TrainingScreen: 'TrainingScreen',
    TrainingVideoScreen: 'TrainingVideoScreen',
    ExploreAllTrainingVideos: 'ExploreAllTrainingVideos',
    ManageToolKitScreen: 'ManageToolKitScreen',
    ReceivedToolkitScreen: 'ReceivedToolkitScreen',
    RequestToolkitScreen: 'RequestToolkitScreen',
    ReturnToolkitScreen: 'ReturnToolkitScreen',
    RatingAndReviewScreen: 'RatingAndReviewScreen',
    AddItemScreen: 'AddItemScreen',
    ServicesScreen: 'ServicesScreen',
    MembershipScreen: 'MembershipScreen',
    PackageScreen: 'PackageScreen',
    DiscountCardScreen: 'DiscountCardScreen',
    GiftCardScreen: 'GiftCardScreen',
    ProductScreen: 'ProductScreen',
    BookingConfirmedScreen: 'BookingConfirmedScreen',
    PaymentMethodScreen: 'PaymentMethodScreen',
    NotificationsScreen:'NotificationsScreen'
}